### PR TITLE
Fix for issue #2

### PR DESCRIPTION
**Pull request by HorizonShadow**
Not entirely sure this is the best way to do this. The (Show more text) button grabs the full text asynchronously. I just removed that event, and rolled my own that included highlighting the text. 

I removed the QSA in favor of a QS because you can't have more than one pre in a message div. Made my life easier with matching the button with the pre.

### CODE REVIEW

**Comment by HorizonShadow** [comment]
dis be broke

**Comment by rlemon** [comment]
wait, what happened here?

**Comment by HorizonShadow** [comment]
Doesn't work right, have to look at it again when I have time.

**Comment by HorizonShadow** [comment]
Oh, I fixed it.

**Comment by rlemon** [comment]
lets put it here on record that I suck at managing branches. So if I end up having to undo this and then add it all back to the master branch by hand don't be too surprised. :-1:

**Pull request closed without merging**
