### PR TITLE
Fixed issue 17

### PR DESCRIPTION
**Pull request by HorizonShadow**
Split hide/show into separate functions, explicitly call hideCodeMode on sayit-button click.

### CODE REVIEW

**Comment by Patsy-issa** [comment]
Can you squash these into 1 commit and add the commit titles to the first commit message?

**Comment by HorizonShadow** [comment]
Rlemon said the banana branch was the correct branch. CodeMode isn't even in the master branch. I'll squash them when I get to work

**Comment by Patsy-issa** [comment]
Ah fair enough :+1:

**Comment by HorizonShadow** [comment]
Branch has been squashed

**Comment by Patsy-issa** [comment]
> Fixes #17

> Removed useless log
Reversed hide/close
Added comments to denote keycodes
Added hideCodeMode function.
Removed toggle from submit button click in favor of `hideCodeMode`

No need for the rest ^^.

**Comment by HorizonShadow** [comment]
Ah, sorry. That was the automatic commit message of `git merge --squash`.

**Comment by Patsy-issa** [comment]
lgtm :beer: cc/ @rlemon

**Comment by rlemon** [comment]
I probably wouldn't have made such a large 'refactor'   

````
function toggleCodeMode(hide = false) {
    if( input.hidden || hide ) {
        //... hide it
    } else {
        //.. show it
    }
}
````

then calling the toggle method passing in true would force hide without having to break the method into three. Both solve the same issue but take a different design approach.

**Comment by HorizonShadow** [comment]
I'd argue adding a default param obscures the function. Turns it from "Toggles the code editor" to "Toggles the code editor, or sets visibility", which is inherently two different functions

**Comment by Patsy-issa** [comment]
I agree with @HorizonShadow, might be a bit more code but readability++

**Comment by Patsy-issa** [comment]
:shipit:

**Pull request merged**
